# Generated by Django 5.1.5 on 2025-10-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(max_length=100)),
                ('subtitulo_blog', models.CharField(max_length=100)),
                ('bg_blog', models.ImageField(blank=True, upload_to='blog/bg/')),
                ('titulo_sobre', models.CharField(max_length=100)),
                ('subtitulo_sobre', models.CharField(max_length=100)),
                ('bg_sobre', models.ImageField(blank=True, upload_to='blog/bg/')),
                ('titulo_contato', models.CharField(max_length=100)),
                ('subtitulo_contato', models.CharField(max_length=100)),
                ('bg_contato', models.ImageField(blank=True, upload_to='blog/bg/')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('bg_image', models.ImageField(blank=True, upload_to='postagens/', verbose_name='Imagem de fundo')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
