# Generated by Django 5.1.5 on 2025-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conteudo_sobre',
            field=models.TextField(default='conteúdo'),
            preserve_default=False,
        ),
    ]
